In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
filterwarnings('ignore')

In [65]:
df=pd.read_csv('SMSSpam',sep='\t',names=['label','message'])
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [66]:
df.shape

(5572, 2)

In [67]:
# replacing unwanted charcters
df['message_new']=df['message'].str.replace('[^a-zA-Z0-9]+',' ')
df.head()

,label,message,message_new
0,ham,"Go until jurong point, crazy.. Available only ...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...,U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",Nah I don t think he goes to usf he lives arou...

In [68]:
# convert to lowercase
df['message_new']=df['message_new'].str.lower()
df.head()

,label,message,message_new
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don t think he goes to usf he lives arou...

In [69]:
# stripping to spaces
df['message_new']=df['message_new'].str.strip()
df.head()

,label,message,message_new
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don t think he goes to usf he lives arou...

In [70]:
df.isnull().sum()

label          0
message        0
message_new    0
dtype: int64

In [71]:
df[df.duplicated()]

,label,message,message_new
103,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request melle melle oru minnaminun...
154,ham,As per your request 'Melle Melle (Oru Minnamin...,as per your request melle melle oru minnaminun...
207,ham,"As I entered my cabin my PA said, '' Happy B'd...",as i entered my cabin my pa said happy b day b...
223,ham,"Sorry, I'll call later",sorry i ll call later
326,ham,No calls..messages..missed calls,no calls messages missed calls
...,...,...,...
5524,spam,You are awarded a SiPix Digital Camera! call 0...,you are awarded a sipix digital camera call 09...
5535,ham,"I know you are thinkin malaria. But relax, chi...",i know you are thinkin malaria but relax child...
5539,ham,Just sleeping..and surfing,just sleeping and surfing
5553,ham,Hahaha..use your brain dear,hahaha use your brain dear
5558,ham,"Sorry, I'll call later",sorry i ll call later

In [72]:
# dropping the duplicates
df.drop_duplicates(inplace=True)

In [73]:
df.shape

(5169, 3)

In [74]:
import nltk
# nltk.download('wordnet')
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [76]:
# stopwords with stemming
corpus=[]
lm=PorterStemmer()
for i in range(len(df)):
    message=df.message_new.iloc[i].split()
    message=[lm.stem(word) for word in message if not word in stopwords.words('english')]
    message=' '.join(message)
    corpus.append(message)
df['stemming']=corpus

In [77]:
df.head()

,label,message,message_new,stemming
0,ham,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,go jurong point crazi avail bugi n great world...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni,ok lar joke wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,u dun say earli hor u c alreadi say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah i don t think he goes to usf he lives arou...,nah think goe usf live around though

In [80]:
print(df.message_new.iloc[1],df.stemming.iloc[1],sep='\n')

ok lar joking wif u oni
ok lar joke wif u oni

In [81]:
# Encoding
df['label']=df['label'].replace({'ham':1,'spam':0})
df.head()

,label,message,message_new,stemming
0,1,"Go until jurong point, crazy.. Available only ...",go until jurong point crazy available only in ...,go jurong point crazi avail bugi n great world...
1,1,Ok lar... Joking wif u oni...,ok lar joking wif u oni,ok lar joke wif u oni
2,0,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,1,U dun say so early hor... U c already then say...,u dun say so early hor u c already then say,u dun say earli hor u c alreadi say
4,1,"Nah I don't think he goes to usf, he lives aro...",nah i don t think he goes to usf he lives arou...,nah think goe usf live around though

In [82]:
from sklearn.model_selection import train_test_split
x=df.stemming
y=df.label
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

## Bag of Words

In [83]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2))

In [84]:
xtrain_cv=cv.fit_transform(xtrain)
xtest_cv=cv.transform(xtest)

In [86]:
cv.get_feature_names()

['00',
 '00 easter',
 '00 per',
 '00 sub',
 '000',
 '000 bonu',
 '000 cash',
 '000 homeown',
 '000 pound',
 '000 price',
 '000 xma',
 '008704050406',
 '008704050406 sp',
 '0089',
 '0089 last',
 '0121',
 '0121 2025050',
 '01223585236',
 '01223585236 xx',
 '0125698789',
 '0125698789 ring',
 '02',
 '02 06',
 '02 09',
 '02 user',
 '0207',
 '0207 083',
 '0207 153',
 '02072069400',
 '02072069400 bx',
 '02073162414',
 '02073162414 cost',
 '02085076972',
 '02085076972 repli',
 '021',
 '021 3680',
 '03',
 '03 05',
 '03 2nd',
 '03 final',
 '03 marsm',
 '04',
 '05',
 '05 05',
 '05 prize',
 '050703',
 '050703 csbcm4235wc1n3xx',
 '0578',
 '06',
 '06 03',
 '06 05',
 '06 11',
 '07',
 '07 11',
 '07046744435',
 '07046744435 arrang',
 '07090201529',
 '07099833605',
 '07099833605 schedul',
 '07123456789',
 '07123456789 87077',
 '0721072',
 '0721072 find',
 '07742676969',
 '07742676969 show',
 '0776xxxxxxx',
 '0776xxxxxxx invit',
 '07781482378',
 '07781482378 com',
 '07786200117',
 '078',
 '07801543489',
 '07801543489 guarante',
 '07808247860',
 '07808247860 show',
 '07808726822',
 '07808726822 award',
 '07815296484',
 '07815296484 show',
 '07821230901',
 '078498',
 '078498 show',
 '07880867867',
 '0789xxxxxxx',
 '0789xxxxxxx today',
 '07946746291',
 '07946746291 07880867867',
 '0796xxxxxx',
 '0796xxxxxx today',
 '07973788240',
 '07973788240 show',
 '07xxxxxxxxx',
 '07xxxxxxxxx 000',
 '07xxxxxxxxx show',
 '08',
 '08 03',
 '0800',
 '0800 0721072',
 '0800 169',
 '0800 18',
 '0800 195',
 '0800 1956669',
 '0800 542',
 '08000407165',
 '08000407165 18',
 '08000776320',
 '08000776320 repli',
 '08000839402',
 '08000839402 2stoptxt',
 '08000839402 call',
 '08000839402 call2optout',
 '08000839402 or2optout',
 '08000930705',
 '08000930705 del',
 '08000930705 deliveri',
 '08000930705 free',
 '08000930705 repli',
 '08000938767',
 '08000938767 updat',
 '08001950382',
 '08001950382 call',
 '08001950382 call2optout',
 '08002888812',
 '08002888812 repli',
 '08002986906',
 '08002988890',
 '08002988890 repli',
 '0808',
 '0808 145',
 '08081263000',
 '08081263000 charg',
 '08081560665',
 '08081560665 speak',
 '0825',
 '083',
 '083 6089',
 '0844',
 '0844 861',
 '08448350055',
 '08448350055 bt',
 '0845',
 '0845 021',
 '08450542832',
 '08452810071',
 '08452810071 16',
 '08452810073',
 '08452810073 detail',
 '08452810075over18',
 '0870',
 '0870 chatlin',
 '0870 nation',
 '08700435505150p',
 '08700469649',
 '08700469649 po',
 '08700621170150p',
 '08700621170150p per',
 '08701213186',
 '08701237397',
 '08701237397 must',
 '08701417012',
 '08701417012 profit',
 '0870141701216',
 '0870141701216 norm',
 '087016248',
 '08701752560',
 '08701752560 450p',
 '0870241182716',
 '0870241182716 wk',
 '08702490080',
 '08702490080 tell',
 '08702840625',
 '08702840625 comuk',
 '08704439680',
 '08704439680 book',
 '08704439680t',
 '08704439680t cs',
 '08706091795',
 '0870737910216yr',
 '0870737910216yr 50',
 '08707509020',
 '08707509020 20p',
 '08708800282',
 '08708800282 hg',
 '08709222922',
 '08709222922 nation',
 '0871',
 '0871 4719',
 '0871 872',
 '08712103738',
 '08712103738 10p',
 '0871212025016',
 '08712300220',
 '08712300220 quot',
 '087123002209am',
 '087123002209am 7pm',
 '08712317606',
 '08712317606 msg150p',
 '08712317606 stop',
 '08712400602450p',
 '08712400602450p provid',
 '08712400603',
 '08712402050',
 '08712402050 line',
 '08712402578',
 '08712402578 immedi',
 '08712402779',
 '08712402779 immedi',
 '08712402902',
 '08712402902 immedi',
 '08712402972',
 '08712402972 immedi',
 '08712404000',
 '08712404000 immedi',
 '08712405020',
 '08712405022',
 '08712405022 1x150p',
 '08712460324',
 '08712460324 10p',
 '08712460324 nat',
 '0871277810910p',
 '0871277810910p min',
 '08714342399',
 '08714342399 2stop',
 '087147123779am',
 '087147123779am 7pm',
 '08714712379',
 '08714712379 10am',
 '08714712388',
 '08714712388 10am',
 '08714712394',
 '08714712394 10am',
 '08714712412',
 '08714712412 10am',
 '08714714011',
 '08715203028',
 '08715203028 claim',
 '08715203649',
 '08715203649 identifi',
 '08715203656',
 '08715203656 identifi',
 '08715203685',
 '08715203685 identifi',
 '08715500022',
 '08715500022 rpl',
 '08717111821',
 '08717168528',
 '08717205546',
 '0871750',
 '0871750 77',
 '08717895698',
 '08717895698 mobstorequiz10ppm',
 '08717898035',
 '08717898035 00',
 '08718720201',
 '08718720201 hg',
 '08718723815',
 '08718725756',
 '08718725756 140ppm',
 '08718726270',
 '087187262701',
 '087187262701 50gbp',
 '08718726971',
 '08718726971 10p',
 '08718726978',
 '08718726978 10p',
 '08718727868',
 '08718727868 18',
 '08718727870',
 '08718727870150ppm',
 '08718730555',
 '08718730555 10p',
 '08718730666',
 '08718730666 10p',
 '08718738001',
 '08718738001 identifi',
 '08718738034',
 '08719180219',
 '08719180219 identifi',
 '08719180248',
 '08719180248 identifi',
 '08719181259',
 '08719181259 identifi',
 '08719181503',
 '08719181513',
 '08719839835',
 '08719839835 futur',
 '08719899229',
 '08719899229 identifi',
 '08719899230',
 '08719899230 identifi',
 '09',
 '09 03',
 '09041940223',
 '09041940223 claim',
 '09050000301',
 '09050000460',
 '09050000460 land',
 '09050000555',
 '09050000555 ba128nnfwfly150ppm',
 '09050000928',
 '09050000928 pobox45w2tg150p',
 '09050001295',
 '09050001295 land',
 '09050002311',
 '09050002311 b4280703',
 '09050003091',
 '09050003091 land',
 '09050005321',
 '09050090044',
 '09050090044 toclaim',
 '09050280520',
 '09050280520 subscrib',
 '09053750005',
 '09053750005 b4',
 '09056242159',
 '09056242159 retriev',
 '09058091854',
 '09058091854 reveal',
 '09058094454',
 '09058094454 land',
 '09058094455',
 '09058094455 land',
 '09058094507',
 '09058094507 land',
 '09058094565',
 '09058094565 land',
 '09058094583',
 '09058094583 book',
 '09058094597',
 '09058094599',
 '09058095107',
 '09058095107 reveal',
 '09058095201',
 '09058095201 land',
 '09058097189',
 '09058097189 reveal',
 '09058097218',
 '09058097218 find',
 '09058099801',
 '09058099801 b4190604',
 '09061104276',
 '09061104276 claim',
 '09061209465',
 '09061209465 suprman',
 '09061213237',
 '09061213237 landlin',
 '09061221061',
 '09061221061 landlin',
 '09061221066',
 '09061221066 fromm',
 '09061701444',
 '09061701444 valid',
 '09061701461',
 '09061701461 claim',
 '09061701939',
 '09061701939 claim',
 '09061702893',
 '09061702893 acl03530150pm',
 '09061743386',
 '09061743806',
 '09061743806 landlin',
 '09061743810',
 '09061743810 landlin',
 '09061749602',
 '09061749602 landlin',
 '09061790126',
 '09061790126 land',
 '09063440451',
 '09063440451 landlin',
 '09063442151',
 '09063442151 claim',
 '09063458130',
 '09063458130 videochat',
 '09064011000',
 '09064011000 ntt',
 '09064017305',
 '09064017305 pobox75ldns7',
 '09064019788',
 '09064019788 box42wr29c',
 '09065069120',
 '09065069154',
 '09065171142',
 '09065171142 stopsm',
 '09065174042',
 '09065174042 opt',
 '09065394514',
 '09065394514 landlin',
 '09065394973',
 '09065394973 landlin',
 '09065989182',
 '09065989182 colour',
 '09066350750',
 '09066350750 landlin',
 '09066358152',
 '09066358152 claim',
 '09066358361',
 '09066358361 land',
 '09066362220',
 '09066362220 asap',
 '09066362231',
 '09066362231 asap',
 '09066364311',
 '09066364311 collect',
 '09066364589',
 '09066368470',
 '09066380611',
 '09066382422',
 '09066382422 call',
 '09066612661',
 '09066612661 landlin',
 '09066660100',
 '09066660100 prize',
 '09071512433',
 '09071512433 b4',
 '09071517866',
 '09071517866 150ppmpobox10183bhamb64x',
 '09077818151',
 '09077818151 book',
 '09090204448',
 '09090204448 join',
 '09094646631',
 '09094646631 60p',
 '09094646899',
 '09094646899 cheap',
 '09095350301',
 '09095350301 send',
 '09096102316',
 '09096102316 cum',
 '09099726395',
 '09099726395 luci',
 '09099726429',
 '09099726429 janinexx',
 '09099726481',
 '09099726481 luv',
 '09701213186',
 '0a',
 '0a network',
 '0quit',
 '0quit edrunk',
 '10',
 '10 000',
 '10 04',
 '10 10',
 '10 30',
 '10 day',
 '10 den',
 '10 kilo',
 '10 leav',
 '10 ls1',
 '10 make',
 '10 man',
 '10 min',
 '10 mth',
 '10 page',
 '10 smth',
 '10 txtauction',
 '100',
 '100 20',
 '100 cash',
 '100 filthi',
 '100 free',
 '100 gift',
 '100 high',
 '100 music',
 '100 percent',
 '100 travel',
 '100 txt',
 '100 weekli',
 '100 wkli',
 '1000',
 '1000 cash',
 '1000 cashto',
 '1000 claim',
 '1000 flirt',
 '1000 girl',
 '1000 gr8',
 '1000 holiday',
 '1000 prize',
 '1000 quiz',
 '1000 text',
 '1000 txt',
 '1000 winner',
 '100p',
 '100p sm',
 '100txt',
 '100txt mth',
 '1013',
 '1013 ig11',
 '1030',
 '1030 den',
 '10am',
 '10am 7pm',
 '10am 9pm',
 '10am till',
 '10k',
 '10k 5k',
 '10p',
 '10p min',
 '10p per',
 '10p repli',
 '10ppm',
 '10ppm 16',
 '10th',
 '10th sept',
 '11',
 '11 04',
 '11 48',
 '11 bt',
 '11 mnth',
 '1120',
 '1120 1205',
 '113',
 '113 bray',
 '1131',
 '1131 standard',
 '1146',
 '1146 mk45',
 '116',
 '116 need',
 '118p',
 '118p msg',
 '11mth',
 '11mth call',
 '11mth entitl',
 '11mth updat',
 '11pm',
 '11pm guarante',
 '12',
 '12 anyway',
 '12 help',
 '12 hour',
 '12 kiosk',
 '12 mth',
 '12 rite',
 '1205',
 '1205 one',
 '120p',
 '121',
 '121 chat',
 '1225',
 '1225 select',
 '123',
 '123 congratul',
 '1250',
 '1250 call',
 '125gift',
 '125gift guarante',
 '128',
 '128 mb',
 '12hr',
 '12hr 150ppm',
 '12mth',
 '12mth 2price',
 '12mth half',
 '13',
 '13 10',
 '130',
 '130 iriv',
 '1327',
 '1327 croydon',
 '140',
 '140 ard',
 '1405',
 '1405 1680',
 '140ppm',
 '145',
 '145 4742',
 '1450',
 '1450 prize',
 '146tf150p',
 '14tcr',
 '14tcr w1',
 '15',
 '15 26',
 '15 tri',
 '150',
 '150 ppm',
 '150 prize',
 '150 sae',
 '150 text',
 '150 textand',
 '150 worth',
 '1500',
 '1500 bonu',
 '150p',
 '150p 08712400603',
 '150p 18',
 '150p daili',
 '150p day',
 '150p inc',
 '150p meg',
 '150p min',
 '150p msg',
 '150p msgrcvd',
 '150p msgrcvdhg',
 '150p mt',
 '150p mtmsg',
 '150p netcollex',
 '150p per',
 '150p poli',
 '150p sm',
 '150p text',
 '150p tone',
 '150p wk',
 '150p16',
 '150pm',
 '150pm dont',
 '150pm unsubscrib',
 '150ppermesssubscript',
 '150ppm',
 '150ppm 16',
 '150ppm 18',
 '150ppm ave',
 '150ppm mobil',
 '150ppm mobilesvari',
 '150ppmpobox10183bhamb64x',
 '150ppmsg',
 '150ppmsg 18',
 '151',
 '151 paus',
 '153',
 '153 9153',
 '15541',
 '15pm',
 '15pm go',
 '16',
 '16 118p',
 '16 99',
 '16 appli',
 '16 close',
 '16 club',
 '16 cs',
 '16 help',
 '16 may',
 '16 need',
 '16 norm150p',
 '16 remov',
 '16 repli',
 '16 sn',
 '16 stop',
 '16 tsandc',
 '16 wk',
 '1680',
 '1680 1843',
 '169',
 '169 6031',
 '177',
 '177 m227xi',
 '18',
 '18 11',
 '18 150p',
 '18 150ppm',
 '18 50',
 '18 8007',
 '18 day',
 '18 legitimat',
 '18 msg',
 '18 opt',
 '18 stop',
 '18 www',
 '18 year',
 '18 yr',
 '180',
 '180 least',
 '1843',
 '1843 big',
 '18p',
 '18p txt',
 '18yr',
 '195',
 '195 6669',
 '1956669',
 '1956669 text',
 '1appl',
 '1appl day',
 '1cup',
 '1cup milk',
 '1da',
 '1da 150ppmsg',
 '1hr',
 '1hr time',
 '1lemon',
 '1lemon day',
 '1pm',
 '1pm orchard',
 '1st',
 '1st 5wkg',
 '1st class',
 '1st get',
 '1st june',
 '1st lor',
 '1st rington',
 '1st salari',
 '1st sept',
 '1st tone',
 '1st ur',
 '1st week',
 '1st wk',
 '1st4term',
 '1st4term pobox84',
 '1stone',
 '1stone sun',
 '1thing',
 '1thing got',
 '1tulsi',
 '1tulsi leaf',
 '1winaweek',
 '1winaweek age16',
 '1winawk',
 '1winawk age16',
 '1x150p',
 '1x150p wk',
 '1yf',
 '1yf 150ppm',
 '20',
 '20 000',
 '20 min',
 '20 poboxox36504w45wq',
 '20 sale',
 '20 salon',
 '20 tone',
 '20 year',
 '200',
 '200 award',
 '200 free',
 '200 prize',
 '200 shop',
 '200 summer',
 '2000',
 '2000 award',
 '2000 bonu',
 '2000 cash',
 '2000 plu',
 '2000 pound',
 '2000 prize',
 '2003',
 '2003 account',
 '2004',
 '2004 account',
 '2004 must',
 '2004 offer',
 '2005',
 '2005 text',
 '2006',
 '2006 fifa',
 '2007',
 '2007 uk',
 '200p',
 '200p 16',
 '2025050',
 '2025050 visit',
 '20m12aq',
 '20m12aq 150ppm',
 '20p',
 '20p min',
 '20p per',
 '21',
 '21 aberdeen',
 '21 invit',
 '21 match',
 '21 may',
 '21870000',
 '21870000 hi',
 '21st',
 '21st instead',
 '21st may',
 '22',
 '22 65',
 '22 day',
 '220',
 '220 cm2',
 '220cm2',
 '220cm2 9ae',
 '2309',
 '24',
 '24 hour',
 '24 hr',
 '24m',
 '24th',
 '24th sept',
 '25',
 '25 18',
 '25 free',
 '25 invit',
 '25 love',
 '25 pass',
 '25 year',
 '250',
 '250 cash',
 '250 gift',
 '250 sm',
 '250 top',
 '250 want',
 '250 weekli',
 '250 wkli',
 '255',
 '255 128',
 '25p',
 '25p alfi',
 '25p free',
 '25p pm',
 '25p see',
 '26',
 '26 03',
 '26 10',
 '26 11',
 '26 sorri',
 '2667',
 '2667 wc1n',
 '26th',
 '26th juli',
 '27',
 '27 03',
 '28',
 '28 day',
 '28 eh74rr',
 '28 soire',
 '28day',
 '28day cs',
 '28thfeb',
 '28thfeb appli',
 '29',
 '29 03',
 '29 invit',
 '2bold',
 '2day',
 '2day 09099726395',
 '2day night',
 '2day normal',
 '2exit',
 '2exit msg',
 '2find',
 '2find log',
 '2getha',
 '2geva',
 '2geva bin',
 '2go',
 '2go 4a',
 '2go thanx',
 '2hr',
 '2hr back',
 '2i',
 '2i feelingood',
 '2kbsubject',
 '2kbsubject low',
 '2land',
 '2land row',
 '2marrow',
 '2marrow come',
 '2marrow wed',
 '2moro',
 '2moro luv',
 '2moro need',
 '2morow',
 '2morow 28',
 '2morow wil',
 '2morro',
 '2morro half',
 '2morrow',
 '2morrow luv',
 '2morrow maga',
 '2morrow take',
 '2mro',
 '2mro come',
 '2mrw',
 '2mrw afternoon',
 '2mrw love',
 '2mrw luv',
 '2mrw ninish',
 '2mwen',
 '2mwen im',
 '2nd',
 '2nd attempt',
 '2nd inning',
 '2nd may',
 '2nd opinion',
 '2nd test',
 '2nd time',
 '2nd ur',
 '2nhite',
 '2nhite ro',
 '2night',
 '2night ur',
 '2nite',
 '2nite 2moro',
 '2nite didnt',
 '2nite sexi',
 '2nite sign',
 '2nite tell',
 '2optout',
 '2optout 087187262701',
 '2optout d3wv',
 '2p',
 '2p per',
 '2price',
 '2price linerent',
 '2rcv',
 '2rcv hlp',
 '2stop',
 '2stop repli',
 '2stop txt',
 '2stoptxt',
 '2stoptxt cs',
 '2u',
 '2u 3wk',
 '2u rpli',
 '2u2',
 '2u2 id',
 '2waxsto',
 '2waxsto wat',
 '2wk',
 '2wk free',
 '2wk way',
 '2wt',
 '2year',
 '2year sent',
 '2yr',
 '2yr messag',
 '2yr warranti',
 '30',
 '30 30',
 '30 ice',
 '30 sec',
 '30 wanna',
 '30 want',
 '30 www',
 '300',
 '300 free',
 '300 nasdaq',
 '3000',
 '3000 award',
 '300603',
 '300603 post',
 '300p',
 '300p one',
 '3030',
 '3030 valid',
 '30apr',
 '30ish',
 '30ish desper',
 '30pm',
 '30pm see',
 '31',
 '31 10',
 '31 decemb',
 '3100',
 '3100 standard',
 '310303',
 '310303 cs',
 '31p',
 '31p msg',
 '32000',
 '32000 award',
 '3230',
 '3230 textbook',
 '326',
 '326 cw25wx',
 '33',
 '33 50',
 '33 65',
 '330',
 '330 hm',
 '350',
 '350 award',
 '350 claim',
 '350 reward',
 '3510i',
 '3510i colour',
 '3650',
 '3650 video',
 '36504',
 '36504 w4',
 '36504 w45wq',
 '3680',
 '3680 offer',
 '373',
 '373 london',
 '3750',
 '3750 pound',
 '38',
 '38 definit',
 '382',
 '382 ubi',
 '3aj',
 '3d',
 '3d imp',
 '3day',
 '3day also',
 '3g',
 '3g lt',
 '3g spotti',
 '3g videophon',
 '3gbp',
 '3gbp network',
 '3hr',
 '3hr 16',
 '3lion',
 '3lion tone',
 '3lp',
 '3lp 50',
 ...]

In [104]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model_cv=lr.fit(xtrain_cv,ytrain)
ypred_cv=model.predict(xtest_cv)
ypred_cv

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [105]:
from sklearn.metrics import accuracy_score,f1_score,classification_report

In [106]:
accuracy_score(ytest,ypred_cv)

0.9742101869761445

In [107]:
f1_score(ytest,ypred_cv)

0.9853587115666178

In [108]:
print(classification_report(ytest,ypred_cv))

              precision    recall  f1-score   support

           0       0.98      0.82      0.89       201
           1       0.97      1.00      0.99      1350

    accuracy                           0.97      1551
   macro avg       0.98      0.91      0.94      1551
weighted avg       0.97      0.97      0.97      1551

## Tfidfvectorizer

In [102]:
# tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
xtrain_tf=tf.fit_transform(xtrain)
xtest_tf=tf.transform(xtest)

In [110]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
model_tf=lr.fit(xtrain_tf,ytrain)
ypred_tf=model_tf.predict(xtest_tf)
ypred_tf

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [111]:
accuracy_score(ytest,ypred_tf)

0.9638942617666022

In [112]:
f1_score(ytest,ypred_tf)

0.9796215429403202

In [113]:
print(classification_report(ytest,ypred_tf))

              precision    recall  f1-score   support

           0       0.97      0.74      0.84       201
           1       0.96      1.00      0.98      1350

    accuracy                           0.96      1551
   macro avg       0.97      0.87      0.91      1551
weighted avg       0.96      0.96      0.96      1551

## Word2vec

In [115]:
from gensim.models import Word2Vec
w2v=Word2Vec

In [133]:
#Build the model
model = Word2Vec( #Word list
#                                min_count=10, #Ignore all words with total frequency lower than this                           
#                                workers=4, #Number of CPU Cores
#                                size=50,  #Embedding size
#                                window=5, #Maximum Distance between current and predicted word
#                                iter=10   #Number of iterations over the text corpus
                              )

In [134]:
model.build_vocab(df.stemming,progress_per=1000)

In [126]:
model.predict_output_word

In [127]:
model

In [128]:
model.wv